# database/init_db.py
"""
init_db.py
creates/updates the DB schema (idempotent)
"""

from __future__ import annotations
import os
from database.connection import get_db

IS_PG = bool(os.getenv("DATABASE_URL", "").strip())

SCHEMA_SQL_PG = """
CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT
);
CREATE TABLE IF NOT EXISTS movies (
    movie_id INTEGER PRIMARY KEY,
    title TEXT NOT NULL,
    year INTEGER,
    genres TEXT,
    poster_url TEXT
);
CREATE TABLE IF NOT EXISTS ratings (
    user_id INTEGER NOT NULL,
    movie_id INTEGER NOT NULL,
    rating DOUBLE PRECISION NOT NULL,
    timestamp BIGINT NOT NULL,
    -- new in Sprint 8
    is_favorite BOOLEAN NOT NULL DEFAULT FALSE,
    in_watchlist BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (user_id, movie_id, timestamp),
    FOREIGN KEY (movie_id) REFERENCES movies(movie_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);
CREATE TABLE IF NOT EXISTS tags (
    user_id INTEGER NOT NULL,
    movie_id INTEGER NOT NULL,
    tag TEXT NOT NULL,
    timestamp BIGINT NOT NULL,
    PRIMARY KEY (user_id, movie_id, tag, timestamp),
    FOREIGN KEY (movie_id) REFERENCES movies(movie_id)
);
CREATE TABLE IF NOT EXISTS links (
    movie_id INTEGER PRIMARY KEY,
    imdb_id INTEGER,
    tmdb_id INTEGER,
    FOREIGN KEY (movie_id) REFERENCES movies(movie_id)
);
CREATE INDEX IF NOT EXISTS idx_ratings_user ON ratings(user_id);
CREATE INDEX IF NOT EXISTS idx_ratings_movie ON ratings(movie_id);
CREATE INDEX IF NOT EXISTS idx_tags_movie ON tags(movie_id);
"""

SCHEMA_SQL_SQLITE = """
PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE,
    password_hash TEXT
);
CREATE TABLE IF NOT EXISTS movies (
    movie_id INTEGER PRIMARY KEY,
    title TEXT NOT NULL,
    year INTEGER,
    genres TEXT,
    poster_url TEXT
);
CREATE TABLE IF NOT EXISTS ratings (
    user_id INTEGER NOT NULL,
    movie_id INTEGER NOT NULL,
    rating REAL NOT NULL,
    timestamp INTEGER NOT NULL,
    -- new in Sprint 8
    is_favorite INTEGER NOT NULL DEFAULT 0,
    in_watchlist INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id, movie_id, timestamp),
    FOREIGN KEY (movie_id) REFERENCES movies(movie_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);
CREATE TABLE IF NOT EXISTS tags (
    user_id INTEGER NOT NULL,
    movie_id INTEGER NOT NULL,
    tag TEXT NOT NULL,
    timestamp INTEGER NOT NULL,
    PRIMARY KEY (user_id, movie_id, tag, timestamp),
    FOREIGN KEY (movie_id) REFERENCES movies(movie_id)
);
CREATE TABLE IF NOT EXISTS links (
    movie_id INTEGER PRIMARY KEY,
    imdb_id INTEGER,
    tmdb_id INTEGER,
    FOREIGN KEY (movie_id) REFERENCES movies(movie_id)
);
CREATE INDEX IF NOT EXISTS idx_ratings_user ON ratings(user_id);
CREATE INDEX IF NOT EXISTS idx_ratings_movie ON ratings(movie_id);
CREATE INDEX IF NOT EXISTS idx_tags_movie ON tags(movie_id);
"""


def _ensure_password_hash_column():
    """Add users.password_hash if an older DB exists."""
    with get_db(readonly=False) as conn:
        cur = conn.cursor()
        # Postgres: simple IF NOT EXISTS
        if IS_PG:
            cur.execute(
                "ALTER TABLE users "
                "ADD COLUMN IF NOT EXISTS password_hash TEXT;"
            )
            return

        # SQLite: check pragma and add only if missing
        cur.execute("PRAGMA table_info(users);")
        cols = [r[1] for r in cur.fetchall()]  # r[1] = name
        if "password_hash" not in cols:
            cur.execute("ALTER TABLE users ADD COLUMN password_hash TEXT;")


def _ensure_fav_watchlist_columns():
    """
    Add ratings.is_favorite and ratings.in_watchlist
    for existing databases that were created before Sprint 8.
    """
    with get_db(readonly=False) as conn:
        cur = conn.cursor()

        if IS_PG:
            # BOOLEAN with default false
            cur.execute(
                "ALTER TABLE ratings "
                "ADD COLUMN IF NOT EXISTS is_favorite BOOLEAN NOT NULL DEFAULT FALSE;"
            )
            cur.execute(
                "ALTER TABLE ratings "
                "ADD COLUMN IF NOT EXISTS in_watchlist BOOLEAN NOT NULL DEFAULT FALSE;"
            )
            return

        # SQLite: inspect schema and add missing columns
        cur.execute("PRAGMA table_info(ratings);")
        cols = [r[1] for r in cur.fetchall()]

        if "is_favorite" not in cols:
            cur.execute(
                "ALTER TABLE ratings "
                "ADD COLUMN is_favorite INTEGER NOT NULL DEFAULT 0;"
            )

        if "in_watchlist" not in cols:
            cur.execute(
                "ALTER TABLE ratings "
                "ADD COLUMN in_watchlist INTEGER NOT NULL DEFAULT 0;"
            )


def main() -> None:
    sql = SCHEMA_SQL_PG if IS_PG else SCHEMA_SQL_SQLITE
    with get_db(readonly=False) as conn:
        cur = conn.cursor()
        for stmt in [s.strip() for s in sql.split(";") if s.strip()]:
            cur.execute(stmt + ";")

    # migrations for older DBs
    _ensure_password_hash_column()
    _ensure_fav_watchlist_columns()

    print("✅ Database schema created/updated")


if __name__ == "__main__":
    main()
